<a href="https://colab.research.google.com/github/Tom-Jung/IO_with_python/blob/main/Ch_%EB%B6%80%EB%A1%9D_RAS_while_loop_1107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [73]:

# np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [74]:
# 2015년 거래표 다운로드

# url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015_tot_cst_3secs.csv"  # 2015년 거래표(benchmark year)
# Tot_15 = pd.read_csv(url_total)
# Tot_15

In [75]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_3_secs_1_va.csv"  # 2019년 거래표(비교연도)
Tot_19 = pd.read_csv(url_Tt_3)
Tot_19_num = Tot_19.to_numpy()
Tot_19

Unnamed: 0   농산품     공산품     서비스   중간수요계      소비     투자     수출   최종수요계  \
0        농산품   4.0    38.0    11.0    53.0    18.0    0.0    1.0    19.0   
1        공산품  16.0   944.0   401.0  1361.0   213.0  167.0  628.0  1008.0   
2        서비스   7.0   257.0   693.0   957.0  1032.0  432.0  131.0  1595.0   
3      중간투입계  27.0  1239.0  1105.0  2371.0  1263.0  599.0  760.0  2622.0   
4      부가가치계  33.0   553.0  1342.0  1928.0     0.0    0.0    0.0     0.0   
5       총투입액  60.0  1792.0  2447.0  4299.0     0.0    0.0    0.0     0.0   

     총수요계  
0    72.0  
1  2369.0  
2  2552.0  
3  4993.0  
4     0.0  
5     0.0

In [76]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Estimated_table.csv"  # 비교연도 거래표
Tot_est = pd.read_csv(url_Tt_3)
Tr = Tot_est.to_numpy()
Tot_est

구분  농산품   공산품   서비스  중간수요계    소비   투자   수출  최종수요계  총수요계
0    농산품    0     0     0     60    19    0    1     20    80
1    공산품    0     0     0   1513   215  170  635   1020  2533
2    서비스    0     0     0   1106  1035  455  130   1620  2726
3  중간투입계   30  1484  1165   2679  1269  625  766   2660  5339
4  부가가치계   35   568  1355   1958     0    0    0      0     0
5   총투입액   65  2052  2520   4637     0    0    0      0     0

In [77]:
Tb = Tot_19_num[0:7,1:10]
Tb

array([[4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       [16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0, 2369.0],
       [7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0, 2552.0],
       [27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0, 2622.0,
        4993.0],
       [33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [78]:
ct = Tb[-1,0:3]  # 산출액
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[60.0, 1792.0, 2447.0],
       [60.0, 1792.0, 2447.0],
       [60.0, 1792.0, 2447.0]], dtype=object)

In [79]:
# At=Tb[0:3,0:3]/ct_m
# At

In [80]:
# ct_ref = Tr[5,1:4]
# aa=np.diag(ct_ref)
# aa

In [81]:
At=Tb[0:3,0:3]/ct_m
row_vec = Tr[0:3,4] # 중간수요계
col_vec = Tr[3, 1:4] # 중간투입계

er = 1
ec = 1
col_vec.shape
col_vec

array([30, 1484, 1165], dtype=object)

In [82]:
Ct_ref = Tr[5,1:4]  # 비교연도 산출액
Ct_ref

array([65, 2052, 2520], dtype=object)

In [83]:
# M = At@np.diag(ct_ref)
# R_sm = M.sum(axis=1)
# R = (row_vec/R_sm)
# # print(M)
# # print(R)
# At = np.diag(R)@At

# M = At@np.diag(ct_ref)
# C_sm = M.sum(axis=0) #열수정계수
# S = (col_vec.T/C_sm)
# At = At@np.diag(S)
# print(C_sm)
# # er = abs(R-1)
# # es = abs(S-1)
# # print(er)
er =1
ec =1

In [84]:
i=0
while True:
  if (er<0.0000001) and (ec<0.0000001):
    break
  M = At@np.diag(ct)
  R_sm = M.sum(axis=1)
  R = (row_vec/R_sm)
  # print(R)
  At = np.diag(R)@At
  print('check------\n',M)

  M = At@np.diag(ct)
  C_sm = M.sum(axis=0) #열수정계수
  S = (col_vec.T/C_sm)
  At = At@np.diag(S)
  print('check------\n',M)
  # print(S)
  er = abs(R-1).sum()
  es = abs(S-1).sum()

  i = i+1
  if er<0.0000001 or ec<0.0000001:
    break
  # print('반복회수', i)
  print(er)
  print(es)
print('반복회수', i)
# er = abs(R.sum()-1)
# ec = abs(C.sum()-1)
#   # print(At)
  # print(er)
  # print(ec)
  # print(col_vec)
  # print(row_vec)

print(At)
Mf = At@np.diag(ct)
df_Mf = pd.DataFrame(Mf)
df_Mf.to_csv('RAS결과.csv')
print(df_Mf)

print(col_vec)
print(row_vec)

check------
 [[4.0 38.0 11.0]
 [16.0 944.0 401.0]
 [7.0 257.0 692.9999999999999]]
check------
 [[4.528301886792453 43.01886792452831 12.452830188679243]
 [17.78692138133725 1049.4283614988979 445.7847171197649]
 [8.089864158829677 297.01358411703245 800.896551724138]]
0.3994529378645024
0.1561241908456915
check------
 [[4.467971254156627 45.94588014132656 11.52184440160723]
 [17.54994596618005 1120.8316731841517 412.457414856404]
 [7.982082779663326 317.2224466745221 741.0207407419889]]
check------
 [[4.328332342106202 44.50991908625815 11.161748571635645]
 [17.121743562404482 1093.4844199441627 402.3938364934325]
 [8.279848359515382 329.05619087181174 768.6639607686727]]
0.09295663330182069
0.03520317757007607
check------
 [[4.367652238532866 45.024161457076055 10.999172811666773]
 [17.277282723981447 1106.1179189957961 396.5327939018663]
 [8.355065037485682 332.8579195471279 757.4680332864667]]
check------
 [[4.3393749542475195 44.73266365832759 10.927961387424892]
 [17.1985310071827